### ISSUE TITLE
Fullstack checklist 

### ISSUE THREAD

**Issue by swei0810** [swei0810/GitIn#1]
# Fullstack Feature Outline
## Backend:
- [ ] Create table  
- [ ] Model 
    - Remember that this holds our associations and any other methods we may need! 
    - Ex.: If I’m working on Warbler and I wanted access to the total number of `likes` a `user` has had on their warbles, I might want a method like `User#total_likes` that will iterate through all `warbles` of a `user`, and sum up all of their `likes`.  Then in my views, I can just call `@user.total_likes` instead of having to manually calculate it. 

- [ ] Controller
- [ ] Views - jbuilder 
  - Think about what information each controller action will need to pass to the state on the front end and modify the controller in order to avoid n+1 queries

## Frontend:
- [ ] Util
- [ ] Action type `const`s and action creators
- [ ] Create and/or modify reducers
  - If you are creating the `sessions` reducer, `errors` reducer, `entities` reducer, or any other top-level reducers, make sure to modify the `root reducer
  - If you are creating a new slice of state that will be under the `entities` key (`users`, or anything else that has a table in your database), modify the `entities` reducer
  - Make sure to modify ALL reducers that will be affected by this new slice of state!
- [ ] Store (if you have not created this already)
- [ ] Components and their containers - think about which components will be connected!
  - If you're comfortable, write html while writing the relevant component’s `render` function so that there is less to refactor 
- [ ] HTML and CSS
